export class ProjectsDB {
  public static projects = [
    {
      id: '2348u23489sdg834',
      projectName: "SFO Terminal 3 West Modernization",
      status: "Postponed",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: true,
      stage: "100% CD Design",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    },
    
    {
      id: '2348u23489sdg8764',
      projectName: "SFO T1C/Boarding Area B",
      status: "Construction",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: true,
      stage: "Closeout",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    },
    {
      id: '65876567534',
      projectName: "Golden Gate Tennis Center",
      status: "Construction",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: true,
      stage: "Closeout",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    },
    {
      id: '767tyfghu54',
      projectName: "Rossi Pool Renovation",
      status: "Construction",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: true,
      stage: "Mobilization",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    },
    {
      id: '767t7656664u54',
      projectName: "Facebook MPK-61",
      status: "Construction",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: true,
      stage: "Installation: Structural",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    },
    {
      id: '32t76578656648h',
      projectName: "Gilead NB 357 Pilot Lab",
      status: "Complete",
      squareFootage: "558997",
      completionDate: "03/17/2021",
      location: "San Francisco, CA",
      isActive: false,
      stage: "Operations & Maintenance",
      dataFile: "./apps/dist/...",
      widgets: [],
      projectPhotoURL: "http://somephoto.com/pic.jpeg",
      projectHeaderURL: "http://somephoto.com/pic.jpeg",
    }
  ]
}
